In [1]:
import numpy as np
import scipy
import scipy.linalg

## Часть 1
### Задание 2

### а)

In [2]:
A = np.array([[3, -1, 1], [2, -5, -3], [1, 1, -1]])
print(f'Матрица A:\n{A}')

A1 = np.array([[3, -1, 1, 4], [2, -5, -3, -17], [1, 1, -1, 0]])
print(f'Расширенная матрица A:\n{A1}')

Матрица A:
[[ 3 -1  1]
 [ 2 -5 -3]
 [ 1  1 -1]]
Расширенная матрица A:
[[  3  -1   1   4]
 [  2  -5  -3 -17]
 [  1   1  -1   0]]


In [3]:
r_A = np.linalg.matrix_rank(A)
print(f'Ранг матрицы A: {r_A}')

r_A1 = np.linalg.matrix_rank(A1)
print(f'Ранг расширенной матрицы A: {r_A1}')

Ранг матрицы A: 3
Ранг расширенной матрицы A: 3


Ранг A равен рангу расширенной матрицы A, следовательно, СЛАУ имеет решение. Данные ранги совпадают с числом неизвестных в СЛАУ, следовательно, решение единственное.

### б)

In [4]:
B = np.array([[2, -4, 6], [1, -2, 3], [3, -6, 9]])
print(f'Матрица B:\n{B}')

B1 = np.array([[2, -4, 6, 1], [1, -2, 3, -2], [3, -6, 9, 5]])
print(f'Расширенная матрица B:\n{B1}')

Матрица B:
[[ 2 -4  6]
 [ 1 -2  3]
 [ 3 -6  9]]
Расширенная матрица B:
[[ 2 -4  6  1]
 [ 1 -2  3 -2]
 [ 3 -6  9  5]]


In [5]:
r_B = np.linalg.matrix_rank(B)
print(f'Ранг матрицы B: {r_B}')

r_B1 = np.linalg.matrix_rank(B1)
print(f'Ранг расширенной матрицы B: {r_B1}')

Ранг матрицы B: 1
Ранг расширенной матрицы B: 2


Ранг матрицы B меньше ранга расширенной матрицы B. Следовательно, СЛАУ несовместна.

### в)

In [6]:
C = np.array([[1, 2, 5], [3, 1, -8]])
print(f'Матрица C:\n{C}')

C1 = C = np.array([[1, 2, 5, 4], [3, 1, -8, -2]])
print(f'Расширенная матрица :\n{C1}')

Матрица C:
[[ 1  2  5]
 [ 3  1 -8]]
Расширенная матрица :
[[ 1  2  5  4]
 [ 3  1 -8 -2]]


In [7]:
r_C = np.linalg.matrix_rank(C)
print(f'Ранг матрицы C: {r_C}')

r_C1 = np.linalg.matrix_rank(C1)
print(f'Ранг расширенной матрицы C: {r_C1}')

Ранг матрицы C: 2
Ранг расширенной матрицы C: 2


Ранг С  равен рангу расширенной матрицы С, следовательно, СЛАУ имееет решение. Данные ранги меньше числа неизвестных в СЛАУ, следовательно, система имеет бесоконечное количество решений.

### Задание 3

In [8]:
A = np.array([[1, 3, -2, 4], [0, 5, 0, 1], [0, 0, 3, 0], [0, 0, 0, 2]])
print(f'Матрица A:\n{A}')

A1 = np.array([[1, 3, -2, 4, 3], [0, 5, 0, 1, 2], [0, 0, 3, 0, 4], [0, 0, 0, 2, 1]])
print(f'Расширенная матрица A:\n{A1}')

Матрица A:
[[ 1  3 -2  4]
 [ 0  5  0  1]
 [ 0  0  3  0]
 [ 0  0  0  2]]
Расширенная матрица A:
[[ 1  3 -2  4  3]
 [ 0  5  0  1  2]
 [ 0  0  3  0  4]
 [ 0  0  0  2  1]]


In [9]:
r_A = np.linalg.matrix_rank(A)
print(f'Ранг матрицы A: {r_A}')

r_A1 = np.linalg.matrix_rank(A1)
print(f'Ранг расширенной матрицы A: {r_A1}')

Ранг матрицы A: 4
Ранг расширенной матрицы A: 4


Ранг А равен рангу расширенной матрицы А, следовательно, СЛАУ имееет решение. Данные ранги совпадают с числом неизвестных в СЛАУ, следовательно, решение единственное.

## Часть 2

### Задание 1

### а)

In [10]:
A = np.array([[1, -2], [3, -4]])
print(f'Матрица A:\n{A}')
print(f'Определитель матрицы A:\n{np.linalg.det(A):.0f}')

Матрица A:
[[ 1 -2]
 [ 3 -4]]
Определитель матрицы A:
2


In [11]:
A1 = np.array([[1, -2], [7, -4]])
print(f'Матрица A1:\n{A1}')
print(f'Определитель матрицы A1:\n{np.linalg.det(A1):.0f}')

Матрица A1:
[[ 1 -2]
 [ 7 -4]]
Определитель матрицы A1:
10


In [12]:
A2 = np.array([[1, 1], [3, 7]])
print(f'Матрица A2:\n{A2}')
print(f'Определитель матрицы A2:\n{np.linalg.det(A2):.0f}')

Матрица A2:
[[1 1]
 [3 7]]
Определитель матрицы A2:
4


Ответ: x1 = 10/2 = 5, x2 = 4/2 = 2 

### б)

In [13]:
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
print(f'Матрица A:\n{a}')
print(f'Определитель матрицы A:\n{np.linalg.det(a):.0f}')

Матрица A:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]
Определитель матрицы A:
43


In [14]:
a1 = np.array([[10, -1, 5], [-2, 1, -3], [1, 4, 1]])
print(f'Матрица A1:\n{a1}')
print(f'Определитель матрицы A1:\n{np.linalg.det(a1):.0f}')

Матрица A1:
[[10 -1  5]
 [-2  1 -3]
 [ 1  4  1]]
Определитель матрицы A1:
86


In [15]:
a2 = np.array([[2, 10, 5], [1, -2, -3], [2, 1, 1]])
print(f'Матрица A2:\n{a2}')
print(f'Определитель матрицы A2:\n{np.linalg.det(a2):.0f}')

Матрица A2:
[[ 2 10  5]
 [ 1 -2 -3]
 [ 2  1  1]]
Определитель матрицы A2:
-43


In [16]:
a3 = np.array([[2, -1, 10], [1, 1, -2], [2, 4, 1]])
print(f'Матрица A3:\n{a3}')
print(f'Определитель матрицы A3:\n{np.linalg.det(a3):.0f}')

Матрица A3:
[[ 2 -1 10]
 [ 1  1 -2]
 [ 2  4  1]]
Определитель матрицы A3:
43


Ответ: x1 = 86/43 = 2, x2 = -43/43 = -1, x3 = 43/43 = 1 

### Задание 3

In [17]:
a = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
print(f'Матрица a:\n{a}')

Матрица a:
[[ 2  1  3]
 [11  7  5]
 [ 9  8  4]]


In [18]:
P, L, U = scipy.linalg.lu(a)

print(f'Матрица P:\n{P}')
print(f'Матрица L:\n{L}')
print(f'Матрица U:\n{U}')

Матрица P:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Матрица L:
[[ 1.          0.          0.        ]
 [ 0.81818182  1.          0.        ]
 [ 0.18181818 -0.12        1.        ]]
Матрица U:
[[11.          7.          5.        ]
 [ 0.          2.27272727 -0.09090909]
 [ 0.          0.          2.08      ]]


In [19]:
b = np.array([1, -6, -5])
b

array([ 1, -6, -5])

Решим систему Ly = b:

In [20]:
y = np.linalg.solve(L, b)
y

array([ 1.        , -6.81818182, -6.        ])

Решим систему Ux= y:

In [21]:
x = np.linalg.solve(U, y)
x

array([ 3.38461538, -3.11538462, -2.88461538])

Осуществим проверку, подставив полученные значения в исходную систему:

In [22]:
np.dot(a, x)

array([-5.,  1., -6.])

### Задание 4

In [23]:
a = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
print(f'Матрица a:\n{a}')

Матрица a:
[[ 81 -45  45]
 [-45  50 -15]
 [ 45 -15  38]]


In [24]:
L = np.linalg.cholesky(a)
L

array([[ 9.,  0.,  0.],
       [-5.,  5.,  0.],
       [ 5.,  2.,  3.]])

In [25]:
b = np.array([531, -460, 193])
b

array([ 531, -460,  193])

Решим систему Ly = b:

In [26]:
y = np.linalg.solve(L, b)
y

array([ 59., -33., -12.])

Решим систему LTx = y:

In [27]:
x = np.linalg.solve(L.T, y)
x

array([ 6., -5., -4.])

Осуществим проверку, подставив полученные значения в исходную систему:

In [29]:
np.dot(a, x)

array([ 531., -460.,  193.])

### Задание 5

Напишите на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

In [30]:
a = np.array([[2, -1, 5], [1, 1, -3], [2, 4, 1]])
print(f'Матрица A:\n{a}')

Матрица A:
[[ 2 -1  5]
 [ 1  1 -3]
 [ 2  4  1]]


In [31]:
b = np.array([10, -2, 1])
b

array([10, -2,  1])

In [32]:
def Cramer(A, B):
    m = len(A)
    det = np.linalg.det(A)
    r = []
    for i in range(m):
        VM = np.copy(A)
        VM[:,i]=B
        r.append(np.linalg.det(VM)/det)
    return r
x = Cramer(a, b)
x

[2.0000000000000018, -1.0000000000000009, 1.0]

Осуществим проверку, подставив полученные значения в исходную систему:

In [33]:
np.dot(a, x)

array([10., -2.,  1.])